# Generated by Django 5.1 on 2024-09-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_profile"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blog",
            table="blog_blog",
        ),
    ]
